### ISSUE TITLE
Unable to specify configuration file path

### ISSUE THREAD

**Issue by arvgord** [yoheimuta/action-protolint#3]
I am trying to specify the path to my `.protolint.yaml` configuration file using the `args` key in the `with` section of the GitHub Action, but it doesn't seem to work. Is there a way to specify the configuration file path in this action? Here's how I'm trying to do it:
https://github.com/arvgord/bank-demo-api/pull/10
```yaml
with:
  args: -config_path=./.protolint.yaml
```
Below is a screenshot of the logs showing how protolint starts without the specified .protolint.yaml file arguments:
![Снимок экрана от 2023-10-28 01-26-25](https://github.com/yoheimuta/action-protolint/assets/39695947/6099904c-79d8-4317-9063-d08b7e3711d0)

**Comment by yoheimuta** [comment]
@arvgord How about setting `protolint_flags: -config_path=./.protolint.yaml .` instead of using `args`?

**Comment by arvgord** [comment]
A set `protolint_flags: -config_path=.protolint.yaml ./bankdemo`.   
However, when I check the logs, I see that the arguments are being passed with single quotes, as shown below:
![Снимок экрана от 2023-10-28 12-19-05](https://github.com/yoheimuta/action-protolint/assets/39695947/69ae7f5f-9090-4cb4-a04d-ffff2b56bf07)
The build went without errors, although they should be:
![Снимок экрана от 2023-10-28 12-26-35](https://github.com/yoheimuta/action-protolint/assets/39695947/9cb67d54-afd8-464c-897d-527b02f97e1b)
This seems to cause protolint to interpret the arguments as a single string, thus not processing the arguments as expected. I have tested the command locally without quotes and it works fine:
![Снимок экрана от 2023-10-28 12-21-58](https://github.com/yoheimuta/action-protolint/assets/39695947/a78f3382-90d8-49f5-aa88-b4be211df85b)
I see warnings as expected.
But with quotes, it does not work:
![Снимок экрана от 2023-10-28 12-22-47](https://github.com/yoheimuta/action-protolint/assets/39695947/d8be200e-852e-4bdd-ad2f-466ce414e96c)

**Comment by arvgord** [comment]
@yoheimuta It would be beneficial if protolint action could default to reading the .protolint.yaml configuration file if it exists in project directory, without requiring the user to specify the path via command-line arguments.

**Comment by arvgord** [comment]
@yoheimuta Could you look at the [PR](https://github.com/yoheimuta/action-protolint/pull/4) please?
